#The name of your workflow.
name:  Build
# Trigger the workflow on push or pull request
on:   
  push:
    branches:
      - master
      - release/**
#A workflow run is made up of one or more jobs. Jobs run in parallel by default.
jobs:
  build:
    if: ${{github.ref == 'refs/tags/**'}}
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          flutter-version: '2.0.4'
          channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --debug --split-per-abi
      env:
        KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        ALIAS: ${{ secrets.ALIAS }}
        STORE_FILE: ${{ secrets.STORE_FILE }}
    - name: Create a Release APK
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.TOKEN }}          